### ISSUE TITLE
Storage folder for markers

### ISSUE THREAD

**Issue by xperseguers** [visol/ext-variables#3]
Going up the page tree to look for markers is great but in addition, it would very useful to be able to configure (via TypoScript) a general storage folder (not recursive) where markers are stored. This could ease the management of such markers.

So markers would first be looked for in general storage folder and then up to the root.

**Comment by dhuf** [comment]
Any news ?

**Comment by jrenggli** [comment]
@xperseguers: Fully agree here. Could you implement that?

**Comment by xperseguers** [comment]
Will be tackled with on Monday 7th.
